// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;

namespace SampleSlideView
{
	public partial class FirstController : UIViewController
	{
		public FirstController(IntPtr handle) : base(handle)
		{
		}

		public override void ViewDidLoad()
		{
			base.ViewDidLoad();
			this.View.BackgroundColor = UIColor.Blue;
		}
	}
}
